import { Inter, Sora } from "next/font/google";
import SharedLayout from "@/components/Shared";
import "./globals.css";

const inter = Inter({
 subsets: ["latin"],
 variable: "--font-inter",
 display: "swap",
});

const sora = Sora({
 subsets: ["latin"],
 variable: "--font-sora",
 display: "swap",
});

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{ children: React.ReactNode }>) {
 return (
  <html lang="pt-br" className={`${inter.variable} ${sora.variable}`}>
   <body>
    <SharedLayout>{children}</SharedLayout>
   </body>
  </html>
 );
}
